{{- $name := include "kubean.name" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubean.fullname" . }}-config
  namespace: {{ include "kubean.namespace" . }}
  labels:
  {{- include "kubean.labels" . | nindent 4}}
data:
  {{- range $key, $value := .Values.kubeanOperator.configMap }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
