{{- if .Values.kubeanOperator.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubean.serviceAccountName" . }}
  namespace: {{ include "kubean.namespace" . }}
  labels:
    kubean.io/kubean-operator: sa
    {{- include "kubean.labels" . | nindent 4 }}
  {{- with .Values.kubeanOperator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
